version: '3.9'
# we'll keep the version for now to work in Compose and Swarm

services:
  db:
    image: postgres:10.0-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  api:
    build: api
    image: dockersamples/wordsmith-api
    depends_on:
      - otel-collector
    deploy:
      replicas: 5
    environment:
      - JAVA_TOOL_OPTIONS="-javaagent:opentelemetry-javaagent.jar"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_SERVICE_NAME=wordsmith-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  web:
    build: web
    image: dockersamples/wordsmith-web
    depends_on:
      - otel-collector
    ports:
     - "8080:80"
    environment:
      - OTEL_SERVICE_NAME=wordsmith-web
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-collector-config.yml]
    environment:
      - NEW_RELIC_LICENSE_KEY
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension